# Application
spring.application.name=campus-nexus

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/campus_nexus
spring.datasource.username=postgres
spring.datasource.password=atharv
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# JWT
jwt.secret=campusnexus_super_secret_key_must_be_256_bits_change_in_production
jwt.access-token-expiry=86400000
jwt.refresh-token-expiry=604800000

# Firebase
firebase.service-account-path=classpath:firebase-service-account.json
firebase.storage-bucket=petzstore-c4f70.firebasestorage.app

# Stripe
stripe.api-key=sk_test_51T9h7lIaEnE73KHPwV0JZF9Hx69tRVzqeZZ5Kff9sHgA2UL0hWNa2W293QMR1vduBBpM1G8H0Q97cEQYtIpuTfPY00mR2SYQKS
stripe.webhook-secret=whsec_HoC7W3jTcWcTY4eVN1g52vyFIkTh0hKe

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Multipart
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

# Cloudinary
cloudinary.cloud-name=dgvk70pgi
cloudinary.api-key=631621241727833
cloudinary.api-secret=wdXj-8sGeXvqk2si27gAAr2RX1U

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Server
server.port=8080

# Ngrok tunnel URL (update this every time ngrok restarts)
app.ngrok-url=https://bleatingly-unvomited-onita.ngrok-free.dev

# Forward headers strategy for ngrok proxy compatibility
server.forward-headers-strategy=framework

# Allow Swagger UI to load from any origin
spring.web.cors.allowed-origins=*
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.try-it-out-enabled=true

# Groq AI (for timetable generation)
groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile
